[2024-09-14T16:41:30.199+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: my_first_dag.transform manual__2024-09-14T16:41:28.319514+00:00 [queued]>
[2024-09-14T16:41:30.203+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: my_first_dag.transform manual__2024-09-14T16:41:28.319514+00:00 [queued]>
[2024-09-14T16:41:30.203+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-14T16:41:30.204+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2024-09-14T16:41:30.204+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-14T16:41:30.210+0000] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): transform> on 2024-09-14 16:41:28.319514+00:00
[2024-09-14T16:41:30.212+0000] {standard_task_runner.py:55} INFO - Started process 3803 to run task
[2024-09-14T16:41:30.214+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'transform', 'manual__2024-09-14T16:41:28.319514+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp7_1pv6bp']
[2024-09-14T16:41:30.215+0000] {standard_task_runner.py:83} INFO - Job 35: Subtask transform
[2024-09-14T16:41:30.245+0000] {task_command.py:389} INFO - Running <TaskInstance: my_first_dag.transform manual__2024-09-14T16:41:28.319514+00:00 [running]> on host 769272fb41c3
[2024-09-14T16:41:30.285+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2024-09-14T16:41:28.319514+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-14T16:41:28.319514+00:00
[2024-09-14T16:41:30.286+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/first_dag.py", line 67, in transform
    for key, value in order_data_dict:
ValueError: too many values to unpack (expected 2)
[2024-09-14T16:41:30.290+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=my_first_dag, task_id=transform, execution_date=20240914T164128, start_date=20240914T164130, end_date=20240914T164130
[2024-09-14T16:41:30.296+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 35 for task transform (too many values to unpack (expected 2); 3803)
[2024-09-14T16:41:30.316+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-14T16:41:30.330+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
