[2024-09-14T19:28:39.712+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: save_city_info_weather_v01.insert_data manual__2024-09-14T19:08:28.214066+00:00 [queued]>
[2024-09-14T19:28:39.734+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: save_city_info_weather_v01.insert_data manual__2024-09-14T19:08:28.214066+00:00 [queued]>
[2024-09-14T19:28:39.734+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-14T19:28:39.735+0000] {taskinstance.py:1284} INFO - Starting attempt 5 of 6
[2024-09-14T19:28:39.736+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-14T19:28:39.747+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): insert_data> on 2024-09-14 19:08:28.214066+00:00
[2024-09-14T19:28:39.752+0000] {standard_task_runner.py:55} INFO - Started process 9573 to run task
[2024-09-14T19:28:39.756+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'save_city_info_weather_v01', 'insert_data', 'manual__2024-09-14T19:08:28.214066+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/saver_info.py', '--cfg-path', '/tmp/tmpxkylvifp']
[2024-09-14T19:28:39.756+0000] {standard_task_runner.py:83} INFO - Job 104: Subtask insert_data
[2024-09-14T19:28:39.822+0000] {task_command.py:389} INFO - Running <TaskInstance: save_city_info_weather_v01.insert_data manual__2024-09-14T19:08:28.214066+00:00 [running]> on host 0c5fe11d0c9c
[2024-09-14T19:28:39.880+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=save_city_info_weather_v01
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2024-09-14T19:08:28.214066+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-14T19:08:28.214066+00:00
[2024-09-14T19:28:39.881+0000] {sql.py:253} INFO - Executing: 
            insert into weathers (id, city_name, max_temp, min_temp, wind, description) values (1,ti.xcom_pull(task_ids="fetcher_data", key="return_value"), '10', '6', '2', 'Kakto')
        
[2024-09-14T19:28:39.900+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-09-14T19:28:40.210+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-09-14T19:28:40.260+0000] {sql.py:364} INFO - Running statement: 
            insert into weathers (id, city_name, max_temp, min_temp, wind, description) values (1,ti.xcom_pull(task_ids="fetcher_data", key="return_value"), '10', '6', '2', 'Kakto')
        , parameters: None
[2024-09-14T19:28:40.267+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 338, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 369, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "task_ids" does not exist
LINE 2: ...n_temp, wind, description) values (1,ti.xcom_pull(task_ids="...
                                                             ^

[2024-09-14T19:28:40.295+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=save_city_info_weather_v01, task_id=insert_data, execution_date=20240914T190828, start_date=20240914T192839, end_date=20240914T192840
[2024-09-14T19:28:40.318+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 104 for task insert_data (column "task_ids" does not exist
LINE 2: ...n_temp, wind, description) values (1,ti.xcom_pull(task_ids="...
                                                             ^
; 9573)
[2024-09-14T19:28:40.356+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-14T19:28:40.433+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
