[2024-09-14T20:04:23.422+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: save_city_info_weather_v01.insert_data manual__2024-09-14T19:44:12.092896+00:00 [queued]>
[2024-09-14T20:04:23.661+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: save_city_info_weather_v01.insert_data manual__2024-09-14T19:44:12.092896+00:00 [queued]>
[2024-09-14T20:04:23.662+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-14T20:04:23.662+0000] {taskinstance.py:1284} INFO - Starting attempt 5 of 6
[2024-09-14T20:04:23.662+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-14T20:04:23.692+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): insert_data> on 2024-09-14 19:44:12.092896+00:00
[2024-09-14T20:04:23.724+0000] {standard_task_runner.py:55} INFO - Started process 12653 to run task
[2024-09-14T20:04:23.734+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'save_city_info_weather_v01', 'insert_data', 'manual__2024-09-14T19:44:12.092896+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/saver_info.py', '--cfg-path', '/tmp/tmpl0_ium8s']
[2024-09-14T20:04:23.742+0000] {standard_task_runner.py:83} INFO - Job 194: Subtask insert_data
[2024-09-14T20:04:23.992+0000] {task_command.py:389} INFO - Running <TaskInstance: save_city_info_weather_v01.insert_data manual__2024-09-14T19:44:12.092896+00:00 [running]> on host 0c5fe11d0c9c
[2024-09-14T20:04:24.093+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=save_city_info_weather_v01
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2024-09-14T19:44:12.092896+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-14T19:44:12.092896+00:00
[2024-09-14T20:04:24.096+0000] {sql.py:253} INFO - Executing: insert into weathers (id, city_name, max_temp, min_temp, wind, description) values (2, '{parameters.name}', '{parameters.max_temp}', '{parameters.min_temp}', '{parameters.wind}', '{parameters.description}')
[2024-09-14T20:04:24.120+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-09-14T20:04:24.429+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-09-14T20:04:24.441+0000] {sql.py:364} INFO - Running statement: insert into weathers (id, city_name, max_temp, min_temp, wind, description) values (2, '{parameters.name}', '{parameters.max_temp}', '{parameters.min_temp}', '{parameters.wind}', '{parameters.description}'), parameters: {'name': '{{ti.xcom_pull(task_ids="fetcher_data", key="return_value")["name"]}}', 'max_temp': '{{ti.xcom_pull(task_ids="fetcher_data", key="return_value")["max_temp"]}}', 'min_temp': '{{ti.xcom_pull(task_ids="fetcher_data", key="return_value")["min_temp"]}}', 'wind': '{{ti.xcom_pull(task_ids="fetcher_data", key="return_value")["wind"]}}', 'description': '{{ti.xcom_pull(task_ids="fetcher_data", key="return_value")["description"]}}'}
[2024-09-14T20:04:24.444+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 338, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 367, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(7)

[2024-09-14T20:04:24.452+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=save_city_info_weather_v01, task_id=insert_data, execution_date=20240914T194412, start_date=20240914T200423, end_date=20240914T200424
[2024-09-14T20:04:24.466+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 194 for task insert_data (value too long for type character varying(7)
; 12653)
[2024-09-14T20:04:24.516+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-14T20:04:24.545+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
