[2024-09-14T20:25:45.263+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: save_city_info_weather_v01.insert_data manual__2024-09-14T20:20:38.094934+00:00 [queued]>
[2024-09-14T20:25:45.270+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: save_city_info_weather_v01.insert_data manual__2024-09-14T20:20:38.094934+00:00 [queued]>
[2024-09-14T20:25:45.270+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-14T20:25:45.270+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 6
[2024-09-14T20:25:45.270+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-14T20:25:45.285+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): insert_data> on 2024-09-14 20:20:38.094934+00:00
[2024-09-14T20:25:45.289+0000] {standard_task_runner.py:55} INFO - Started process 14467 to run task
[2024-09-14T20:25:45.292+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'save_city_info_weather_v01', 'insert_data', 'manual__2024-09-14T20:20:38.094934+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/saver_info.py', '--cfg-path', '/tmp/tmpktmv3d57']
[2024-09-14T20:25:45.293+0000] {standard_task_runner.py:83} INFO - Job 226: Subtask insert_data
[2024-09-14T20:25:45.345+0000] {task_command.py:389} INFO - Running <TaskInstance: save_city_info_weather_v01.insert_data manual__2024-09-14T20:20:38.094934+00:00 [running]> on host 0c5fe11d0c9c
[2024-09-14T20:25:45.400+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=save_city_info_weather_v01
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2024-09-14T20:20:38.094934+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-14T20:20:38.094934+00:00
[2024-09-14T20:25:45.402+0000] {sql.py:253} INFO - Executing: insert into weathers (id, city_name, max_temp, min_temp, wind, description) values (2, '{params['/name/']}', '{params.max_temp}', '{params.min_temp}', '{params.wind}', '{params.description}')
[2024-09-14T20:25:45.407+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-09-14T20:25:45.567+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-09-14T20:25:45.588+0000] {sql.py:364} INFO - Running statement: insert into weathers (id, city_name, max_temp, min_temp, wind, description) values (2, '{params['/name/']}', '{params.max_temp}', '{params.min_temp}', '{params.wind}', '{params.description}'), parameters: None
[2024-09-14T20:25:45.593+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 338, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 369, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "name" does not exist
LINE 1: ...in_temp, wind, description) values (2, '{params['/name/']}',...
                                                             ^

[2024-09-14T20:25:45.601+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=save_city_info_weather_v01, task_id=insert_data, execution_date=20240914T202038, start_date=20240914T202545, end_date=20240914T202545
[2024-09-14T20:25:45.610+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 226 for task insert_data (column "name" does not exist
LINE 1: ...in_temp, wind, description) values (2, '{params['/name/']}',...
                                                             ^
; 14467)
[2024-09-14T20:25:45.635+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-14T20:25:45.646+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
