[2024-09-14T16:36:20.322+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: my_first_dag.extract manual__2024-09-14T16:36:19.616902+00:00 [queued]>
[2024-09-14T16:36:20.328+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: my_first_dag.extract manual__2024-09-14T16:36:19.616902+00:00 [queued]>
[2024-09-14T16:36:20.328+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-14T16:36:20.328+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2024-09-14T16:36:20.328+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-14T16:36:20.336+0000] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2024-09-14 16:36:19.616902+00:00
[2024-09-14T16:36:20.339+0000] {standard_task_runner.py:55} INFO - Started process 3357 to run task
[2024-09-14T16:36:20.343+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'extract', 'manual__2024-09-14T16:36:19.616902+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp9yhqml1v']
[2024-09-14T16:36:20.344+0000] {standard_task_runner.py:83} INFO - Job 28: Subtask extract
[2024-09-14T16:36:20.381+0000] {task_command.py:389} INFO - Running <TaskInstance: my_first_dag.extract manual__2024-09-14T16:36:19.616902+00:00 [running]> on host 769272fb41c3
[2024-09-14T16:36:20.417+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2024-09-14T16:36:19.616902+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-14T16:36:19.616902+00:00
[2024-09-14T16:36:23.872+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/first_dag.py", line 58, in extract
    order_data_dict = json.loads(data_string)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-09-14T16:36:23.883+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=my_first_dag, task_id=extract, execution_date=20240914T163619, start_date=20240914T163620, end_date=20240914T163623
[2024-09-14T16:36:23.896+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 28 for task extract (Expecting value: line 1 column 1 (char 0); 3357)
[2024-09-14T16:36:23.905+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-14T16:36:23.935+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
