[2024-09-14T18:02:13.241+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: save_city_info_weather.save_city_info_weather manual__2024-09-14T18:02:11.229000+00:00 [queued]>
[2024-09-14T18:02:13.250+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: save_city_info_weather.save_city_info_weather manual__2024-09-14T18:02:11.229000+00:00 [queued]>
[2024-09-14T18:02:13.250+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-14T18:02:13.250+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2024-09-14T18:02:13.250+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-14T18:02:13.258+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): save_city_info_weather> on 2024-09-14 18:02:11.229000+00:00
[2024-09-14T18:02:13.262+0000] {standard_task_runner.py:55} INFO - Started process 2301 to run task
[2024-09-14T18:02:13.264+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'save_city_info_weather', 'save_city_info_weather', 'manual__2024-09-14T18:02:11.229000+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/saver_info.py', '--cfg-path', '/tmp/tmp2_u_c9eg']
[2024-09-14T18:02:13.265+0000] {standard_task_runner.py:83} INFO - Job 53: Subtask save_city_info_weather
[2024-09-14T18:02:13.301+0000] {task_command.py:389} INFO - Running <TaskInstance: save_city_info_weather.save_city_info_weather manual__2024-09-14T18:02:11.229000+00:00 [running]> on host 0c5fe11d0c9c
[2024-09-14T18:02:13.343+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=save_city_info_weather
AIRFLOW_CTX_TASK_ID=save_city_info_weather
AIRFLOW_CTX_EXECUTION_DATE=2024-09-14T18:02:11.229000+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-14T18:02:11.229000+00:00
[2024-09-14T18:02:13.344+0000] {sql.py:253} INFO - Executing: 
            if not exists weathers (
                id INTEGER PRIMARY KEY AUTOINCREMENT
                city_name character varying
                max_temp character varying
                min_temp character varying
                wind character varying
                description character varying
            )
        
[2024-09-14T18:02:13.348+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-09-14T18:02:13.487+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-09-14T18:02:21.503+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 331, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.local" to address: Temporary failure in name resolution

[2024-09-14T18:02:21.524+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=save_city_info_weather, task_id=save_city_info_weather, execution_date=20240914T180211, start_date=20240914T180213, end_date=20240914T180221
[2024-09-14T18:02:21.543+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 53 for task save_city_info_weather (could not translate host name "host.docker.local" to address: Temporary failure in name resolution
; 2301)
[2024-09-14T18:02:21.581+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-14T18:02:21.638+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
